"""Markdown report writer. Everything in the report comes from the analysis summary."""

# SHARED NUMBER FORMATTER, SO NUMBERS IN THE REPORT LOOK EXACTLY LIKE THE NUMBERS IN THE FACTS.
from llm import fmt


def _md_escape(x):
    # MAKE A VALUE SAFE FOR A MARKDOWN TABLE CELL: ESCAPE "|" (IT WOULD START A NEW COLUMN) AND REMOVE LINE BREAKS.
    return str(x).replace("|", "\\|").replace("\n", " ")


def _table(headers, rows):
    # BUILD A MARKDOWN TABLE: A HEADER ROW, A "|---|---|" SEPARATOR ROW, THEN ONE ROW PER ITEM.
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(_md_escape(c) for c in r) + " |")
    return "\n".join(out)


def write_report(summary, insights, verification, path):
    # THE REPORT IS BUILT AS A LIST OF LINES (`L`) AND WRITTEN TO `report.md` AT THE END. EVERYTHING COMES FROM THE
    # SUMMARY DICTIONARY - NOTHING IS TYPED IN BY HAND.
    ov, q = summary["overview"], summary["data_quality"]
    L = []
    # TITLE AND A NOTE THAT PYTHON COMPUTED THE STATISTICS.
    L.append(f"# Automated Data Profile: `{ov['filename']}`\n")
    L.append(f"*Generated by `profiler.py` on {summary['generated_at']}. All statistics were computed in Python "
             f"(pandas/NumPy); the language model only explains them.*\n")
    # ONE LINE SAYING WHAT HAPPENED WITH THE LANGUAGE MODEL: USED (WITH HOW MANY INSIGHTS PASSED), TURNED OFF BY THE
    # USER, OR UNAVAILABLE (THE REQUIRED "AI NARRATIVE WAS SKIPPED" MESSAGE, WITH THE ERROR).
    llm = summary["llm"]
    if llm["status"] == "used":
        L.append(f"**AI narrative:** generated with local Ollama model `{llm['model']}`; "
                 f"{llm['verified_count']} of {llm['returned_count']} model insights passed Python verification.\n")
    elif llm["status"] == "disabled":
        L.append("**AI narrative:** disabled by the user (`use_llm=False`). The insights below are Python-generated templates.\n")
    else:
        L.append(f"**AI narrative:** AI-generated narrative insights were skipped because the model was unavailable "
                 f"({llm.get('error')}). The deterministic profile below is complete; insights are Python-generated templates.\n")

    # 1. OVERVIEW
    # FILE NAME, ROW AND COLUMN COUNTS, ROLE COUNTS, AND A TABLE WITH ONE ROW PER COLUMN (TYPE, ROLE, MISSING %, UNIQUE, NOTES).
    L.append("## 1. Dataset overview\n")
    L.append(f"- **File:** `{ov['filename']}`\n- **Rows:** {fmt(ov['rows'])}\n- **Columns:** {fmt(ov['columns'])}\n"
             f"- **Column roles:** " + ", ".join(f"{k} ({v})" for k, v in ov["role_counts"].items()) + "\n")
    rows = [[c["column"], c["technical_type"], c["role"], fmt(c["non_missing"]), f"{c['missing_pct']}%",
             fmt(c["unique"]), "; ".join(c["notes"])] for c in summary["columns"]]
    L.append(_table(["Column", "Technical type", "Probable role", "Non-missing", "Missing %", "Unique", "Notes"], rows))
    L.append("\n*Roles are structural guesses (parse rates, cardinality, text length, generic name hints). "
             "The profiler does not know what any column means, its units, or its valid range.*\n")

    # 2. DATA QUALITY
    # HEADLINE COUNTS: DUPLICATES, MISSING CELLS, CONSTANT AND EMPTY COLUMNS, AND THE THRESHOLD USED.
    L.append("## 2. Data quality profile\n")
    L.append(f"- **Duplicate rows:** {fmt(q['duplicate_rows'])} ({q['duplicate_rows_pct']}%)")
    L.append(f"- **Missing cells:** {fmt(q['total_missing_cells'])} ({q['total_missing_cells_pct']}% of all cells); "
             f"rows with any missing value: {fmt(q['rows_with_any_missing'])} ({q['rows_with_any_missing_pct']}%)")
    L.append(f"- **Constant columns (one distinct value):** " + (", ".join(f"`{c}`" for c in q["constant_columns"]) or "none"))
    L.append(f"- **Completely empty columns:** " + (", ".join(f"`{c}`" for c in q["empty_columns"]) or "none"))
    L.append(f"- **High-missingness threshold:** {q['high_missing_threshold_pct']:.0f}% of rows\n")
    # TABLE OF COLUMNS ABOVE THE MISSINGNESS THRESHOLD (OR A SENTENCE SAYING THERE ARE NONE).
    if q["high_missing_columns"]:
        L.append(_table(["Column above threshold", "Missing", "Missing %"],
                        [[h["column"], fmt(h["missing"]), f"{h['missing_pct']}%"] for h in q["high_missing_columns"]]))
        L.append("")
    else:
        L.append("No column exceeds the high-missingness threshold.\n")
    # MIXED-TYPE TABLE WITH EXAMPLES OF THE VALUES THAT DO NOT FIT.
    L.append("**Mixed / inconsistent types**\n")
    if q["mixed_type_columns"]:
        L.append(_table(["Column", "Inferred type", "Non-conforming values", "% of non-missing", "Examples"],
                        [[m["column"], m["technical_type"], fmt(m["non_conforming_count"]), f"{m['non_conforming_pct']}%",
                          ", ".join(m["examples"])] for m in q["mixed_type_columns"]]))
        L.append("")
    else:
        L.append("None detected.\n")
    # IDENTIFIER / HIGH-CARDINALITY TABLE.
    L.append("**Identifier-like or high-cardinality columns**\n")
    if q["identifier_or_high_cardinality_columns"]:
        L.append(_table(["Column", "Role", "Unique values", "Unique / non-missing"],
                        [[h["column"], h["role"], fmt(h["unique"]), h["unique_ratio"]]
                         for h in q["identifier_or_high_cardinality_columns"]]))
        L.append("")
    else:
        L.append("None detected.\n")
    # PLACEHOLDER-VALUE TABLE (E.G. "NOT AVAILABLE" X 6).
    L.append("**Possible placeholder values** (text such as `unknown`, `N/A`, `-999` that may mean missing; *not* converted)\n")
    if q["possible_placeholder_values"]:
        L.append(_table(["Column", "Count", "% of rows", "Values"],
                        [[p["column"], fmt(p["count"]), f"{p['pct']}%", ", ".join(f"{k} ({v})" for k, v in p["values"].items())]
                         for p in q["possible_placeholder_values"]]))
        L.append("")
    else:
        L.append("None detected.\n")
    # SENSITIVE-FIELD TABLE, FOLLOWED BY THE REQUIRED WARNING THAT NO WARNING DOES NOT MEAN THE DATA ARE SAFE,
    # AND A REMINDER THAT NOTHING WAS DELETED OR CHANGED.
    L.append("**Potentially sensitive fields (heuristic)**\n")
    if q["sensitive_field_warnings"]:
        L.append(_table(["Column", "Why flagged"], [[s["column"], "; ".join(s["reasons"])] for s in q["sensitive_field_warnings"]]))
        L.append("")
    else:
        L.append("No column triggered the name/value heuristics.\n")
    L.append("> ⚠️ Sensitive-field detection is a heuristic based on column names and a few value patterns. "
             "The absence of a warning does **not** mean the dataset is free of personal or sensitive information.\n")
    L.append("> Nothing was deleted, imputed or corrected: duplicates, missing values and outliers are flagged only.\n")

    # 3. DESCRIPTIVE STATISTICS
    # NUMERIC TABLE: ONE ROW PER NUMERIC MEASURE WITH EVERY REQUIRED STATISTIC. MODE SHOWS "—" WHEN IT IS NOT MEANINGFUL.
    L.append("## 3. Descriptive statistics\n")
    L.append("### 3.1 Numeric columns\n")
    ns = summary["numeric_statistics"]
    if ns:
        rows = []
        for c, s in ns.items():
            if not s.get("valid_count"):
                continue
            mode = f"{fmt(s['mode'])} (×{fmt(s['mode_count'])})" if s.get("mode") is not None else "—"
            rows.append([c, fmt(s["valid_count"]), f"{fmt(s['missing_count'])} ({s['missing_pct']}%)", fmt(s["min"]),
                         fmt(s["max"]), fmt(s["mean"]), fmt(s["median"]), mode, fmt(s["std"]), fmt(s["q1"]), fmt(s["q3"]),
                         fmt(s["iqr"]), f"{fmt(s['outlier_count'])} ({s['outlier_pct']}%)"])
        L.append(_table(["Column", "Valid", "Missing", "Min", "Max", "Mean", "Median", "Mode", "Std", "Q1", "Q3", "IQR",
                         "Outliers (1.5×IQR)"], rows))
        # EXPLAIN HOW STD, QUARTILES, OUTLIERS AND MODE WERE CALCULATED, THEN LIST COLUMNS THAT ARE MOSTLY ZEROS.
        L.append("\n*Std is the sample standard deviation (ddof = 1). Quartiles use linear interpolation. "
                 "Outliers are values below Q1 − 1.5×IQR or above Q3 + 1.5×IQR; they are potential outliers to review, "
                 "not errors, and were not removed. Mode is shown only when a value repeats and most values are not unique.*\n")
        notes = [f"`{c}`: {fmt(s['zero_count'])} zeros ({s['zero_pct']}%)" for c, s in ns.items()
                 if s.get("zero_pct", 0) >= 30]
        if notes:
            L.append("**Columns where 30% or more of values are exactly 0** (could be real zeros or placeholders): "
                     + "; ".join(notes) + "\n")
    # NO NUMERIC COLUMNS: SAY THE ANALYSIS WAS SKIPPED (REQUIRED WHEN A DATASET HAS NONE).
    else:
        L.append("*Skipped: no numeric measure columns were found.*\n")

    # ONE SMALL TABLE PER CATEGORICAL/BOOLEAN COLUMN: THE TOP VALUES WITH COUNTS AND %, PLUS ONE "ALL OTHER VALUES" ROW.
    L.append("### 3.2 Categorical and Boolean columns\n")
    cs = summary["categorical_statistics"]
    if cs:
        for c, s in cs.items():
            head = f"**`{c}`** ({s['role']}) — {fmt(s['unique'])} distinct values, {fmt(s['valid_count'])} non-missing, " \
                   f"{s['missing_pct']}% missing. Most frequent: {', '.join(s['most_frequent'][:3])} ({fmt(s['most_frequent_count'])} rows)."
            L.append(head + "\n")
            rows = [[t["value"], fmt(t["count"]), f"{t['pct_of_non_missing']}%"] for t in s["top_values"]]
            if s["other_count"]:
                rows.append([f"(all other {fmt(s['unique'] - s['shown'])} values)", fmt(s["other_count"]),
                             f"{s['other_pct_of_non_missing']}%"])
            L.append(_table(["Value", "Count", "% of non-missing"], rows))
            L.append("")
    else:
        L.append("*Skipped: no categorical or Boolean columns were found.*\n")

    # DATE TABLE: EARLIEST AND LATEST VALUE AND THE TIME BUCKET USED FOR THE TIME PLOT.
    L.append("### 3.3 Date-like columns\n")
    ds = summary["date_statistics"]
    if ds:
        L.append(_table(["Column", "Valid", "Missing %", "Earliest", "Latest", "Granularity used"],
                        [[c, fmt(s["valid_count"]), f"{s['missing_pct']}%", s.get("min"), s.get("max"), s.get("granularity")]
                         for c, s in ds.items()]))
        L.append("")
    else:
        L.append("*Skipped: no date-like columns were found.*\n")

    # LIST COLUMNS THAT GET NO STATISTICS (IDENTIFIERS, FREE TEXT, MIXED) SO THE READER KNOWS THEY WERE NOT FORGOTTEN.
    other = [c for c in summary["columns"] if c["role"] in ("Identifier-like field", "Free-text field", "Unknown or mixed type")]
    if other:
        L.append("### 3.4 Columns not summarized statistically\n")
        L.append(_table(["Column", "Role", "Why"],
                        [[c["column"], c["role"], "identifiers/free text/mixed values are profiled for quality only"] for c in other]))
        L.append("")

    # 4. RELATIONSHIPS
    # EITHER THE REASON CORRELATION WAS SKIPPED, OR: METHOD, COLUMNS USED AND EXCLUDED, THE TOP 5 PAIRS, THE STRONGEST
    # POSITIVE AND NEGATIVE PAIR, THE NEAR-DUPLICATE COUNT, AND THE "CORRELATION IS NOT CAUSATION" NOTE.
    L.append("## 4. Relationships between variables\n")
    rel = summary["relationships"]
    if rel.get("skipped"):
        L.append(f"*Skipped: {rel['skipped']}.*\n")
    else:
        L.append(f"Method: {rel['method']}. Columns used: {', '.join(f'`{c}`' for c in rel['numeric_columns_used'])}.")
        if rel["excluded_from_correlation"]:
            L.append(f"Excluded numeric-typed columns (identifiers, years, flags, constants, or beyond the column cap): "
                     f"{', '.join(f'`{c}`' for c in rel['excluded_from_correlation'])}.\n")
        L.append("**Strongest pairs by |r|**\n")
        L.append(_table(["Column A", "Column B", "Pearson r", "Spearman rho", "Rows used"],
                        [[p["col_a"], p["col_b"], f"{p['pearson_r']:.3f}", fmt(p["spearman_rho"], 3), fmt(p["n_pairs"])]
                         for p in rel["top_pairs_by_abs_r"]]))
        L.append("")
        for label, key in (("Strongest positive", "strongest_positive"), ("Strongest negative", "strongest_negative")):
            if rel[key]:
                p = rel[key][0]
                L.append(f"- **{label}:** `{p['col_a']}` & `{p['col_b']}` (r = {p['pearson_r']:.3f}, n = {fmt(p['n_pairs'])})")
            else:
                L.append(f"- **{label}:** none found")
        if rel["near_duplicate_pairs"]:
            L.append(f"- {len(rel['near_duplicate_pairs'])} pair(s) have |r| ≥ 0.95 — these columns may be derived from "
                     f"each other or measure nearly the same thing.")
        L.append(f"\n> {rel['note']}\n")
    # GROUP-COMPARISON TABLE (MEDIAN AND MEAN OF A MEASURE PER CATEGORY).
    gc = summary.get("group_comparison")
    if gc:
        L.append(f"**`{gc['measure']}` by `{gc['group_column']}`** (top groups by count)\n")
        L.append(_table(["Group", "Rows", "Median", "Mean"],
                        [[g["group"], fmt(g["count"]), fmt(g["median"]), fmt(g["mean"])] for g in gc["groups"]]))
        L.append("")

    # 5. VISUALIZATIONS
    # EMBED EACH SAVED PLOT WITH A CAPTION SAYING WHY IT WAS CHOSEN, THEN A TABLE OF PLOT TYPES THAT WERE SKIPPED AND WHY.
    L.append("## 5. Visualizations\n")
    for i, p in enumerate(summary["plots"], 1):
        L.append(f"**Figure {i}. {p['title']}** — chosen because it shows {p['why']}.\n")
        L.append(f"![{p['title']}]({p['file']})\n")
    if summary["plots_skipped"]:
        L.append("**Plot types skipped**\n")
        L.append(_table(["Plot", "Reason"], [[s["plot"], s["reason"]] for s in summary["plots_skipped"]]))
        L.append("")

    # 6. INSIGHTS
    # THE FINAL 5-8 INSIGHTS. EACH SHOWS ITS CATEGORY, ITS EVIDENCE (CITED FACT IDS, PLUS ANY MATCHED BY PYTHON), AND
    # WHETHER IT CAME FROM THE MODEL (VERIFIED) OR FROM A PYTHON TEMPLATE.
    L.append("## 6. Evidence-based insights\n")
    L.append("Each insight cites fact IDs from `analysis_summary.json → llm_facts`. "
             "Every number in an insight was checked by Python against those facts before it was included.\n")
    for i, ins in enumerate(insights, 1):
        src = "LLM, verified" if ins.get("source") == "llm" else "Python template"
        ids = ins.get("fact_ids", []) + [f"{a} (matched by Python)" for a in ins.get("auto_fact_ids", [])]
        L.append(f"{i}. **[{ins['category']}]** {ins['text']}  \n   *Evidence: {', '.join(ids) or 'n/a'} · Source: {src}*")
    L.append("")

    # CLAIM-VERIFICATION TABLE: EVERY INSIGHT THE MODEL RETURNED - INCLUDING REJECTED ONES - WITH ITS SUPPORTING FACT,
    # ITS STATUS, AND THE REASON FOR ANY REJECTION. THIS IS THE AUDIT TRAIL FOR THE LLM STEP.
    if verification:
        L.append("### Claim-verification table (all model insights)\n")
        L.append(_table(["#", "Category", "Model insight", "Cited facts", "Supporting statistic (computed by Python)",
                         "Status", "Checks"],
                        [[i, v["category"], v["text"],
                          ", ".join(v["fact_ids"] + [f"{a} (auto)" for a in v.get("auto_fact_ids", [])]) or "none",
                          " / ".join(e[:220] for e in v["evidence"]) or "—", v["status"],
                          "; ".join(v["problems"]) or "all numbers match cited facts"]
                         for i, v in enumerate(verification, 1)]))
        L.append("\nREJECTED insights are left out of the list above. At most 2 verified model insights per category are used; "
                 "Python template insights fill any required category the model did not cover.\n")

    # 7. LIMITATIONS
    # EVERY SKIPPED ANALYSIS AND THE STANDING LIMITATIONS, THEN THE LIST OF OUTPUT FILES.
    L.append("## 7. Skipped analyses and limitations\n")
    for s in summary["skipped_analyses"]:
        L.append(f"- Skipped: {s}")
    for lim in summary["limitations"]:
        L.append(f"- {lim}")
    L.append("\n## 8. Files produced\n")
    L.append("- `report.md` (this file), `column_profile.csv`, `analysis_summary.json`, `llm_prompt.txt`, "
             "`llm_response.txt`, and `plots/`.\n")
    # WRITE THE WHOLE REPORT TO DISK AS UTF-8 (NEEDED FOR SYMBOLS LIKE ×, —, ≥ ON WINDOWS).
    path.write_text("\n".join(L), encoding="utf-8")
